//! IUPAC 命名の定数テーブル (S2.1)。
//!
//! **自動生成ファイル — 手で編集しないこと。**
//! 生成元: src/smiles2iupac/constants.py と __init__.py の _RETAINED_NAMES
//! 再生成: uv run python tools/gen_constants_rs.py

use std::collections::HashMap;
use std::sync::LazyLock;

/// 官能基の命名メタデータ (Python FunctionalGroupSpec 相当)。
#[derive(Debug, Clone, Copy)]
pub struct FunctionalGroupSpec {
    /// IUPAC P-65 seniority order (高いほど優先)
    pub priority: i32,
    /// 接尾語 (例: "ol", "one", "oic acid")
    pub suffix: &'static str,
    /// 鎖状ベース名テンプレート (多重結合なし; {stem} {loc})
    pub chain_template: &'static str,
    /// 鎖状ベース名テンプレート (多重結合あり; {stem} {mb} {loc})
    pub chain_template_mb: &'static str,
    /// suffix に位置ロカントが必要か
    pub needs_locant: bool,
    /// 官能基炭素を常に C1 に固定するか
    pub anchor_c1: bool,
    /// 環状化合物テンプレート ({ring} {loc})
    pub cyclic_template: Option<&'static str>,
    /// ベンゼン環直結時の保留名
    pub benzene_name: Option<&'static str>,
}

/// 官能基テーブル (P-65 順は priority を参照)。
pub static FUNCTIONAL_GROUPS: &[(&str, FunctionalGroupSpec)] = &[
    (
        "carboxylic_acid",
        FunctionalGroupSpec {
            priority: 100,
            suffix: "oic acid",
            chain_template: "{stem}anoic acid",
            chain_template_mb: "{stem}{mb}oic acid",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: Some("cyclo{stem}ane-{loc}-carboxylic acid"),
            benzene_name: Some("benzoic acid"),
        },
    ),
    (
        "peroxyacid",
        FunctionalGroupSpec {
            priority: 99,
            suffix: "peroxoic acid",
            chain_template: "{stem}aneperoxoic acid",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "nitrile",
        FunctionalGroupSpec {
            priority: 80,
            suffix: "nitrile",
            chain_template: "{stem}anenitrile",
            chain_template_mb: "{stem}{mb}nitrile",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: Some("cyclo{stem}ane-{loc}-carbonitrile"),
            benzene_name: Some("benzonitrile"),
        },
    ),
    (
        "dinitrile",
        FunctionalGroupSpec {
            priority: 80,
            suffix: "dinitrile",
            chain_template: "{stem}anedinitrile",
            chain_template_mb: "{stem}{mb}edinitrile",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "aldehyde",
        FunctionalGroupSpec {
            priority: 70,
            suffix: "al",
            chain_template: "{stem}anal",
            chain_template_mb: "{stem}{mb}al",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: Some("cyclo{stem}ane-{loc}-carbaldehyde"),
            benzene_name: Some("benzaldehyde"),
        },
    ),
    (
        "thioaldehyde",
        FunctionalGroupSpec {
            priority: 69,
            suffix: "thial",
            chain_template: "{stem}anethial",
            chain_template_mb: "{stem}{mb}ethial",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "dial",
        FunctionalGroupSpec {
            priority: 70,
            suffix: "dial",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "ketone",
        FunctionalGroupSpec {
            priority: 60,
            suffix: "one",
            chain_template: "{stem}an-{loc}-one",
            chain_template_mb: "{stem}{mb}-{loc}-one",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: Some("cyclo{stem}an-{loc}-one"),
            benzene_name: None,
        },
    ),
    (
        "thioketone",
        FunctionalGroupSpec {
            priority: 59,
            suffix: "thione",
            chain_template: "{stem}ane-{loc}-thione",
            chain_template_mb: "{stem}{mb}e-{loc}-thione",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: Some("cyclo{stem}ane-{loc}-thione"),
            benzene_name: None,
        },
    ),
    (
        "imine",
        FunctionalGroupSpec {
            priority: 55,
            suffix: "imine",
            chain_template: "{stem}an-{loc}-imine",
            chain_template_mb: "{stem}{mb}-{loc}-imine",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: Some("cyclo{stem}an-{loc}-imine"),
            benzene_name: None,
        },
    ),
    (
        "diimine",
        FunctionalGroupSpec {
            priority: 55,
            suffix: "diimine",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "ketoxime",
        FunctionalGroupSpec {
            priority: 54,
            suffix: "one oxime",
            chain_template: "{stem}an-{loc}-one oxime",
            chain_template_mb: "{stem}{mb}-{loc}-one oxime",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: Some("cyclo{stem}an-{loc}-one oxime"),
            benzene_name: None,
        },
    ),
    (
        "aldoxime",
        FunctionalGroupSpec {
            priority: 54,
            suffix: "al oxime",
            chain_template: "{stem}anal oxime",
            chain_template_mb: "{stem}{mb}al oxime",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: Some("benzaldoxime"),
        },
    ),
    (
        "alcohol",
        FunctionalGroupSpec {
            priority: 50,
            suffix: "ol",
            chain_template: "{stem}an-{loc}-ol",
            chain_template_mb: "{stem}{mb}-{loc}-ol",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: Some("cyclo{stem}an-{loc}-ol"),
            benzene_name: Some("phenol"),
        },
    ),
    (
        "sulfonate_ester",
        FunctionalGroupSpec {
            priority: 87,
            suffix: "sulfonate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfinate_ester",
        FunctionalGroupSpec {
            priority: 86,
            suffix: "sulfinate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfoxide",
        FunctionalGroupSpec {
            priority: 32,
            suffix: "sulfoxide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfone",
        FunctionalGroupSpec {
            priority: 33,
            suffix: "sulfone",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfonyl_azide",
        FunctionalGroupSpec {
            priority: 44,
            suffix: "sulfonyl azide",
            chain_template: "{stem}anesulfonyl azide",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfonohydrazide",
        FunctionalGroupSpec {
            priority: 43,
            suffix: "sulfonohydrazide",
            chain_template: "{stem}anesulfonohydrazide",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfonamide",
        FunctionalGroupSpec {
            priority: 42,
            suffix: "sulfonamide",
            chain_template: "{stem}anesulfonamide",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "disulfonamide",
        FunctionalGroupSpec {
            priority: 42,
            suffix: "disulfonamide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfinylhydrazide",
        FunctionalGroupSpec {
            priority: 42,
            suffix: "sulfinylhydrazide",
            chain_template: "{stem}anesulfinylhydrazide",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfinamide",
        FunctionalGroupSpec {
            priority: 41,
            suffix: "sulfinamide",
            chain_template: "{stem}anesulfinamide",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfonic_acid",
        FunctionalGroupSpec {
            priority: 65,
            suffix: "sulfonic acid",
            chain_template: "{stem}anesulfonic acid",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfonate_anion",
        FunctionalGroupSpec {
            priority: 65,
            suffix: "sulfonate",
            chain_template: "{stem}anesulfonate",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "disulfonic_acid",
        FunctionalGroupSpec {
            priority: 65,
            suffix: "disulfonic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "carbonate",
        FunctionalGroupSpec {
            priority: 91,
            suffix: "carbonate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "carbonothioate",
        FunctionalGroupSpec {
            priority: 90,
            suffix: "carbonothioate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "carbonodithioate",
        FunctionalGroupSpec {
            priority: 90,
            suffix: "carbonodithioate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfinic_acid",
        FunctionalGroupSpec {
            priority: 58,
            suffix: "sulfinic acid",
            chain_template: "{stem}anesulfinic acid",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfenic_acid",
        FunctionalGroupSpec {
            priority: 57,
            suffix: "sulfenic acid",
            chain_template: "{stem}anesulfenic acid",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfenyl_halide",
        FunctionalGroupSpec {
            priority: 76,
            suffix: "sulfenyl chloride",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfenate_ester",
        FunctionalGroupSpec {
            priority: 74,
            suffix: "sulfenate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfide",
        FunctionalGroupSpec {
            priority: 30,
            suffix: "sulfide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "thiol",
        FunctionalGroupSpec {
            priority: 45,
            suffix: "thiol",
            chain_template: "{stem}ane-{loc}-thiol",
            chain_template_mb: "{stem}{mb}-{loc}-thiol",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: Some("cyclo{stem}ane-{loc}-thiol"),
            benzene_name: Some("benzenethiol"),
        },
    ),
    (
        "selenol",
        FunctionalGroupSpec {
            priority: 44,
            suffix: "selenol",
            chain_template: "{stem}ane-{loc}-selenol",
            chain_template_mb: "{stem}{mb}-{loc}-selenol",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: Some("cyclo{stem}ane-{loc}-selenol"),
            benzene_name: None,
        },
    ),
    (
        "tellurol",
        FunctionalGroupSpec {
            priority: 43,
            suffix: "tellurol",
            chain_template: "{stem}ane-{loc}-tellurol",
            chain_template_mb: "{stem}{mb}-{loc}-tellurol",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: Some("cyclo{stem}ane-{loc}-tellurol"),
            benzene_name: None,
        },
    ),
    (
        "amine",
        FunctionalGroupSpec {
            priority: 40,
            suffix: "amine",
            chain_template: "{stem}an-{loc}-amine",
            chain_template_mb: "{stem}{mb}-{loc}-amine",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: Some("cyclo{stem}anamine"),
            benzene_name: Some("aniline"),
        },
    ),
    (
        "alkene",
        FunctionalGroupSpec {
            priority: 20,
            suffix: "ene",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "alkyne",
        FunctionalGroupSpec {
            priority: 15,
            suffix: "yne",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "dioic_acid",
        FunctionalGroupSpec {
            priority: 100,
            suffix: "dioic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "diol",
        FunctionalGroupSpec {
            priority: 50,
            suffix: "diol",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "dithiol",
        FunctionalGroupSpec {
            priority: 45,
            suffix: "dithiol",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "triol",
        FunctionalGroupSpec {
            priority: 50,
            suffix: "triol",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "tetraol",
        FunctionalGroupSpec {
            priority: 50,
            suffix: "tetraol",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "pentaol",
        FunctionalGroupSpec {
            priority: 50,
            suffix: "pentaol",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "hexaol",
        FunctionalGroupSpec {
            priority: 50,
            suffix: "hexaol",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "dione",
        FunctionalGroupSpec {
            priority: 60,
            suffix: "dione",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "trione",
        FunctionalGroupSpec {
            priority: 59,
            suffix: "trione",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "tetraone",
        FunctionalGroupSpec {
            priority: 58,
            suffix: "tetraone",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "pentaone",
        FunctionalGroupSpec {
            priority: 57,
            suffix: "pentaone",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "acyl_azide",
        FunctionalGroupSpec {
            priority: 93,
            suffix: "azide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "amide",
        FunctionalGroupSpec {
            priority: 95,
            suffix: "amide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: Some("cyclo{stem}ane-{loc}-carboxamide"),
            benzene_name: Some("benzamide"),
        },
    ),
    (
        "diamide",
        FunctionalGroupSpec {
            priority: 95,
            suffix: "diamide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "hydrazide",
        FunctionalGroupSpec {
            priority: 94,
            suffix: "hydrazide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "thiohydrazide",
        FunctionalGroupSpec {
            priority: 94,
            suffix: "thiohydrazide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "selenohydrazide",
        FunctionalGroupSpec {
            priority: 94,
            suffix: "selenohydrazide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "semicarbazone",
        FunctionalGroupSpec {
            priority: 96,
            suffix: "one semicarbazone",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "aldsemicarbazone",
        FunctionalGroupSpec {
            priority: 96,
            suffix: "al semicarbazone",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "thiosemicarbazone",
        FunctionalGroupSpec {
            priority: 96,
            suffix: "one thiosemicarbazone",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "aldthiosemicarbazone",
        FunctionalGroupSpec {
            priority: 96,
            suffix: "al thiosemicarbazone",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "anhydride",
        FunctionalGroupSpec {
            priority: 88,
            suffix: "anhydride",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "imidic_acid",
        FunctionalGroupSpec {
            priority: 89,
            suffix: "imidic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "imidate_ester",
        FunctionalGroupSpec {
            priority: 87,
            suffix: "imidate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "peroxy_ester",
        FunctionalGroupSpec {
            priority: 95,
            suffix: "peroxoate",
            chain_template: "{stem}aneperoxoate",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "ester",
        FunctionalGroupSpec {
            priority: 90,
            suffix: "oate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "diester",
        FunctionalGroupSpec {
            priority: 90,
            suffix: "dioate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "acid_halide",
        FunctionalGroupSpec {
            priority: 85,
            suffix: "oyl halide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "diacid_halide",
        FunctionalGroupSpec {
            priority: 85,
            suffix: "dioyl halide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "alkane",
        FunctionalGroupSpec {
            priority: 0,
            suffix: "ane",
            chain_template: "{stem}ane",
            chain_template_mb: "{stem}ane",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: Some("cyclo{stem}ane"),
            benzene_name: Some("benzene"),
        },
    ),
    (
        "dithioamide",
        FunctionalGroupSpec {
            priority: 93,
            suffix: "dithioamide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "diselenoamide",
        FunctionalGroupSpec {
            priority: 92,
            suffix: "diselenoamide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "thioamide",
        FunctionalGroupSpec {
            priority: 93,
            suffix: "thioamide",
            chain_template: "{stem}anethioamide",
            chain_template_mb: "{stem}{mb}thioamide",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: Some("cyclo{stem}ane-{loc}-carbothioamide"),
            benzene_name: Some("benzothioamide"),
        },
    ),
    (
        "o_thiocarbamate",
        FunctionalGroupSpec {
            priority: 94,
            suffix: "carbamothioate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "s_carbamothioate",
        FunctionalGroupSpec {
            priority: 94,
            suffix: "carbamothioate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "s_carbamodithioate",
        FunctionalGroupSpec {
            priority: 94,
            suffix: "carbamodithioate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "selenoamide",
        FunctionalGroupSpec {
            priority: 92,
            suffix: "selenoamide",
            chain_template: "{stem}aneselenoamide",
            chain_template_mb: "{stem}{mb}selenoamide",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: Some("cyclo{stem}ane-{loc}-carboselenoamide"),
            benzene_name: Some("benzeneselenoamide"),
        },
    ),
    (
        "telluramide",
        FunctionalGroupSpec {
            priority: 91,
            suffix: "teluramide",
            chain_template: "{stem}aneteluramide",
            chain_template_mb: "{stem}{mb}teluramide",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: Some("cyclo{stem}ane-{loc}-carboteluramide"),
            benzene_name: Some("benzeneteluramide"),
        },
    ),
    (
        "carbamate",
        FunctionalGroupSpec {
            priority: 89,
            suffix: "carbamate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "kethydrazone",
        FunctionalGroupSpec {
            priority: 53,
            suffix: "one hydrazone",
            chain_template: "{stem}an-{loc}-one hydrazone",
            chain_template_mb: "{stem}{mb}-{loc}-one hydrazone",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "aldhydrazone",
        FunctionalGroupSpec {
            priority: 53,
            suffix: "al hydrazone",
            chain_template: "{stem}anal hydrazone",
            chain_template_mb: "{stem}{mb}al hydrazone",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: Some("benzaldehyde hydrazone"),
        },
    ),
    (
        "hydroperoxide",
        FunctionalGroupSpec {
            priority: 47,
            suffix: "hydroperoxide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "peroxide",
        FunctionalGroupSpec {
            priority: 46,
            suffix: "peroxide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "thioester",
        FunctionalGroupSpec {
            priority: 88,
            suffix: "thioate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "o_thioester",
        FunctionalGroupSpec {
            priority: 88,
            suffix: "thioate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "s_dithioate_ester",
        FunctionalGroupSpec {
            priority: 88,
            suffix: "dithioate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "disulfide",
        FunctionalGroupSpec {
            priority: 25,
            suffix: "disulfide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "trisulfide",
        FunctionalGroupSpec {
            priority: 24,
            suffix: "trisulfide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "tetrasulfide",
        FunctionalGroupSpec {
            priority: 23,
            suffix: "tetrasulfide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "selenoxide",
        FunctionalGroupSpec {
            priority: 30,
            suffix: "selenoxide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "selenone",
        FunctionalGroupSpec {
            priority: 31,
            suffix: "selenone",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "selenide",
        FunctionalGroupSpec {
            priority: 29,
            suffix: "selenide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "diselenide",
        FunctionalGroupSpec {
            priority: 24,
            suffix: "diselenide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "telluride",
        FunctionalGroupSpec {
            priority: 28,
            suffix: "telluride",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "ditelluride",
        FunctionalGroupSpec {
            priority: 23,
            suffix: "ditelluride",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfamide",
        FunctionalGroupSpec {
            priority: 41,
            suffix: "",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfamic_acid",
        FunctionalGroupSpec {
            priority: 64,
            suffix: "",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "nitroso",
        FunctionalGroupSpec {
            priority: 30,
            suffix: "nitroso",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "azide",
        FunctionalGroupSpec {
            priority: 35,
            suffix: "azide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "isocyanate",
        FunctionalGroupSpec {
            priority: 40,
            suffix: "isocyanate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "diisocyanate",
        FunctionalGroupSpec {
            priority: 40,
            suffix: "diisocyanate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "diisothiocyanate",
        FunctionalGroupSpec {
            priority: 39,
            suffix: "diisothiocyanate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "diamine",
        FunctionalGroupSpec {
            priority: 95,
            suffix: "diamine",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "triamine",
        FunctionalGroupSpec {
            priority: 95,
            suffix: "triamine",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: true,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfonyl_chloride",
        FunctionalGroupSpec {
            priority: 84,
            suffix: "sulfonyl chloride",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfinyl_chloride",
        FunctionalGroupSpec {
            priority: 83,
            suffix: "sulfinyl chloride",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "isothiocyanate",
        FunctionalGroupSpec {
            priority: 39,
            suffix: "isothiocyanate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "cyanate",
        FunctionalGroupSpec {
            priority: 38,
            suffix: "cyanate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "thiocyanate",
        FunctionalGroupSpec {
            priority: 50,
            suffix: "thiocyanate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "amidine",
        FunctionalGroupSpec {
            priority: 96,
            suffix: "imidamide",
            chain_template: "{stem}animidamide",
            chain_template_mb: "{stem}{mb}imidamide",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: Some("cyclo{stem}ane-{loc}-carboximidamide"),
            benzene_name: Some("benzenecarboximidamide"),
        },
    ),
    (
        "carbamic_acid",
        FunctionalGroupSpec {
            priority: 99,
            suffix: "",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "carbodiimide",
        FunctionalGroupSpec {
            priority: 36,
            suffix: "carbodiimide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "isocyanide",
        FunctionalGroupSpec {
            priority: 37,
            suffix: "isocyanide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "chloroformate",
        FunctionalGroupSpec {
            priority: 86,
            suffix: "carbonochloridate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "ammonium",
        FunctionalGroupSpec {
            priority: 11,
            suffix: "azanium",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphanium",
        FunctionalGroupSpec {
            priority: 11,
            suffix: "phosphanium",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "sulfonium",
        FunctionalGroupSpec {
            priority: 11,
            suffix: "sulfonium",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "arsonium",
        FunctionalGroupSpec {
            priority: 11,
            suffix: "arsonium",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "carboxylate",
        FunctionalGroupSpec {
            priority: 97,
            suffix: "oate",
            chain_template: "{stem}anoate",
            chain_template_mb: "{stem}{mb}oate",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: Some("benzoate"),
        },
    ),
    (
        "dicarboxylate",
        FunctionalGroupSpec {
            priority: 97,
            suffix: "dioate",
            chain_template: "{stem}anedioate",
            chain_template_mb: "{stem}{mb}dioate",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphate_ester",
        FunctionalGroupSpec {
            priority: 87,
            suffix: "phosphate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphonate_halfester",
        FunctionalGroupSpec {
            priority: 86,
            suffix: "phosphonate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphonate_ester",
        FunctionalGroupSpec {
            priority: 86,
            suffix: "phosphonate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphinate_ester",
        FunctionalGroupSpec {
            priority: 85,
            suffix: "phosphinate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphonic_acid",
        FunctionalGroupSpec {
            priority: 92,
            suffix: "phosphonic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphinic_acid",
        FunctionalGroupSpec {
            priority: 91,
            suffix: "phosphinic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "arsane_org",
        FunctionalGroupSpec {
            priority: 10,
            suffix: "arsane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "organomercury",
        FunctionalGroupSpec {
            priority: 6,
            suffix: "mercury",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "arsonic_acid",
        FunctionalGroupSpec {
            priority: 88,
            suffix: "arsonic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "arsinic_acid",
        FunctionalGroupSpec {
            priority: 87,
            suffix: "arsinic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "arsonous_acid",
        FunctionalGroupSpec {
            priority: 57,
            suffix: "arsonous acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "arsinous_acid",
        FunctionalGroupSpec {
            priority: 56,
            suffix: "arsinous acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphonous_acid",
        FunctionalGroupSpec {
            priority: 56,
            suffix: "phosphonous acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphinous_acid",
        FunctionalGroupSpec {
            priority: 55,
            suffix: "phosphinous acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphane",
        FunctionalGroupSpec {
            priority: 10,
            suffix: "phosphane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphine_oxide",
        FunctionalGroupSpec {
            priority: 60,
            suffix: "phosphine oxide",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "phosphite_ester",
        FunctionalGroupSpec {
            priority: 84,
            suffix: "phosphite",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "boronic_acid",
        FunctionalGroupSpec {
            priority: 90,
            suffix: "boronic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "boronate_ester",
        FunctionalGroupSpec {
            priority: 86,
            suffix: "boronate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "borinic_acid",
        FunctionalGroupSpec {
            priority: 89,
            suffix: "borinic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "borane_org",
        FunctionalGroupSpec {
            priority: 9,
            suffix: "borane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "borate_ester",
        FunctionalGroupSpec {
            priority: 8,
            suffix: "borane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "silane_org",
        FunctionalGroupSpec {
            priority: 8,
            suffix: "silane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "silyl_ether_org",
        FunctionalGroupSpec {
            priority: 8,
            suffix: "silane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "disilane_org",
        FunctionalGroupSpec {
            priority: 8,
            suffix: "disilane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "disiloxane_org",
        FunctionalGroupSpec {
            priority: 8,
            suffix: "disiloxane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "disilazane_org",
        FunctionalGroupSpec {
            priority: 8,
            suffix: "disilazane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "germane_org",
        FunctionalGroupSpec {
            priority: 8,
            suffix: "germane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "stannane_org",
        FunctionalGroupSpec {
            priority: 8,
            suffix: "stannane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "bismuthane_org",
        FunctionalGroupSpec {
            priority: 7,
            suffix: "bismuthane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "stibane_org",
        FunctionalGroupSpec {
            priority: 7,
            suffix: "stibane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "plumbane_org",
        FunctionalGroupSpec {
            priority: 7,
            suffix: "plumbane",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "selenonic_acid",
        FunctionalGroupSpec {
            priority: 78,
            suffix: "selenonic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "seleninic_acid",
        FunctionalGroupSpec {
            priority: 77,
            suffix: "seleninic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "selenenic_acid",
        FunctionalGroupSpec {
            priority: 76,
            suffix: "selenenic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "telluronic_acid",
        FunctionalGroupSpec {
            priority: 78,
            suffix: "telluronic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "tellurinic_acid",
        FunctionalGroupSpec {
            priority: 77,
            suffix: "tellurinic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "tellurenic_acid",
        FunctionalGroupSpec {
            priority: 76,
            suffix: "tellurenic acid",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "silanol_org",
        FunctionalGroupSpec {
            priority: 9,
            suffix: "silanol",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "thioic_s_acid",
        FunctionalGroupSpec {
            priority: 98,
            suffix: "thioic S-acid",
            chain_template: "{stem}anethioic S-acid",
            chain_template_mb: "{stem}{mb}thioic S-acid",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "thioic_o_acid",
        FunctionalGroupSpec {
            priority: 98,
            suffix: "thioic O-acid",
            chain_template: "{stem}anethioic O-acid",
            chain_template_mb: "{stem}{mb}thioic O-acid",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "dithioic_acid",
        FunctionalGroupSpec {
            priority: 98,
            suffix: "dithioic acid",
            chain_template: "{stem}anedithioic acid",
            chain_template_mb: "{stem}{mb}dithioic acid",
            needs_locant: false,
            anchor_c1: true,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "nitrate_ester",
        FunctionalGroupSpec {
            priority: 88,
            suffix: "nitrate",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
    (
        "nitrite_ester",
        FunctionalGroupSpec {
            priority: 87,
            suffix: "nitrite",
            chain_template: "",
            chain_template_mb: "",
            needs_locant: false,
            anchor_c1: false,
            cyclic_template: None,
            benzene_name: None,
        },
    ),
];

/// 官能基名 → spec の索引。
pub static FUNCTIONAL_GROUP_MAP: LazyLock<HashMap<&'static str, &'static FunctionalGroupSpec>> =
    LazyLock::new(|| FUNCTIONAL_GROUPS.iter().map(|(k, v)| (*k, v)).collect());

/// Python FUNCTIONAL_GROUP_PRIORITY 相当。
pub fn functional_group_priority(name: &str) -> Option<i32> {
    FUNCTIONAL_GROUP_MAP.get(name).map(|s| s.priority)
}

/// Python SUFFIX_MAP 相当。
pub fn suffix_of(name: &str) -> Option<&'static str> {
    FUNCTIONAL_GROUP_MAP.get(name).map(|s| s.suffix)
}

/// 炭素数 → 語幹 (meth, eth, ...)。インデックス 0 は未使用。
pub static CHAIN_PREFIX: [&str; 31] = [
    "", "meth", "eth", "prop", "but", "pent", "hex", "hept", "oct", "non", "dec", "undec", "dodec",
    "tridec", "tetradec", "pentadec", "hexadec", "heptadec", "octadec", "nonadec", "icos",
    "henicos", "docos", "tricos", "tetracos", "pentacos", "hexacos", "heptacos", "octacos",
    "nonacos", "triacont",
];

/// 倍数接頭辞 (di, tri, ...)。インデックス 0 は未使用、1 は空。
pub static MULTIPLIER: [&str; 11] = [
    "", "", "di", "tri", "tetra", "penta", "hexa", "hepta", "octa", "nona", "deca",
];

/// ハロゲン接頭辞。
pub fn halogen_prefix(symbol: &str) -> Option<&'static str> {
    match symbol {
        "F" => Some("fluoro"),
        "Cl" => Some("chloro"),
        "Br" => Some("bromo"),
        "I" => Some("iodo"),
        _ => None,
    }
}

/// 母音で始まる接尾語 (直前の 'e' を落とす判定に使用)。
pub static VOWEL_SUFFIXES: [&str; 7] = ["al", "ane", "ene", "oic acid", "ol", "one", "yne"];

/// 保留名テーブル (生 SMILES キー)。ルックアップ時は Rust 側の
/// 正規化キー (canonical_key) で再キー化して使う — RDKit の正規形とは
/// 独立に自己完結させるため (RUST_PORT_PLAN.md 基本方針 5)。
pub static RETAINED_NAMES_RAW: &[(&str, &str)] = &[
    ("C[C@H](N)C(=O)O", "(2S)-2-aminopropanoic acid"),
    ("C[C@@H](N)C(=O)O", "(2R)-2-aminopropanoic acid"),
    ("CC(N)C(=O)O", "alanine"),
    ("CC(C)[C@H](N)C(=O)O", "(2S)-2-amino-3-methylbutanoic acid"),
    ("CC(C)[C@@H](N)C(=O)O", "(2R)-2-amino-3-methylbutanoic acid"),
    ("CC(C)C(N)C(=O)O", "valine"),
    (
        "CC(C)C[C@H](N)C(=O)O",
        "(2S)-2-amino-4-methylpentanoic acid",
    ),
    (
        "CC(C)C[C@@H](N)C(=O)O",
        "(2R)-2-amino-4-methylpentanoic acid",
    ),
    ("CC(C)CC(N)C(=O)O", "leucine"),
    (
        "CC[C@H](C)[C@H](N)C(=O)O",
        "(2S,3S)-2-amino-3-methylpentanoic acid",
    ),
    ("O=C(O)[C@@H]1CCCN1", "(2S)-pyrrolidine-2-carboxylic acid"),
    ("O=C(O)[C@H]1CCCN1", "(2R)-pyrrolidine-2-carboxylic acid"),
    ("OC(=O)C1CCCN1", "proline"),
    (
        "N[C@@H](Cc1ccccc1)C(=O)O",
        "(2S)-2-amino-3-phenylpropanoic acid",
    ),
    (
        "N[C@H](Cc1ccccc1)C(=O)O",
        "(2R)-2-amino-3-phenylpropanoic acid",
    ),
    ("NC(Cc1ccccc1)C(=O)O", "phenylalanine"),
    (
        "N[C@@H](Cc1c[nH]c2ccccc12)C(=O)O",
        "(2S)-2-amino-3-(1H-indol-3-yl)propanoic acid",
    ),
    (
        "N[C@H](Cc1c[nH]c2ccccc12)C(=O)O",
        "(2R)-2-amino-3-(1H-indol-3-yl)propanoic acid",
    ),
    (
        "CSCC[C@H](N)C(=O)O",
        "(2S)-2-amino-4-methylsulfanylbutanoic acid",
    ),
    (
        "CSCC[C@@H](N)C(=O)O",
        "(2R)-2-amino-4-methylsulfanylbutanoic acid",
    ),
    ("CSCCC(N)C(=O)O", "methionine"),
    ("N[C@@H](CO)C(=O)O", "(2S)-2-amino-3-hydroxypropanoic acid"),
    ("N[C@H](CO)C(=O)O", "(2R)-2-amino-3-hydroxypropanoic acid"),
    ("NC(CO)C(=O)O", "serine"),
    (
        "C[C@H](O)[C@H](N)C(=O)O",
        "(2S,3S)-2-amino-3-hydroxybutanoic acid",
    ),
    (
        "C[C@@H](O)[C@@H](N)C(=O)O",
        "(2R,3R)-2-amino-3-hydroxybutanoic acid",
    ),
    ("N[C@@H](CS)C(=O)O", "(2R)-2-amino-3-sulfanylpropanoic acid"),
    ("N[C@H](CS)C(=O)O", "(2S)-2-amino-3-sulfanylpropanoic acid"),
    ("NC(CS)C(=O)O", "cysteine"),
    (
        "N[C@@H](Cc1ccc(O)cc1)C(=O)O",
        "(2S)-2-amino-3-(4-hydroxyphenyl)propanoic acid",
    ),
    (
        "N[C@H](Cc1ccc(O)cc1)C(=O)O",
        "(2R)-2-amino-3-(4-hydroxyphenyl)propanoic acid",
    ),
    (
        "NC(=O)C[C@H](N)C(=O)O",
        "(2S)-2,4-diamino-4-oxobutanoic acid",
    ),
    (
        "NC(=O)C[C@@H](N)C(=O)O",
        "(2R)-2,4-diamino-4-oxobutanoic acid",
    ),
    ("NC(=O)CC(N)C(=O)O", "asparagine"),
    (
        "NC(=O)CC[C@H](N)C(=O)O",
        "(2S)-2,5-diamino-5-oxopentanoic acid",
    ),
    (
        "NC(=O)CC[C@@H](N)C(=O)O",
        "(2R)-2,5-diamino-5-oxopentanoic acid",
    ),
    ("NC(=O)CCC(N)C(=O)O", "glutamine"),
    ("NCCCC[C@H](N)C(=O)O", "(2S)-2,6-diaminohexanoic acid"),
    ("NCCCC[C@@H](N)C(=O)O", "(2R)-2,6-diaminohexanoic acid"),
    ("NCCCCC(N)C(=O)O", "lysine"),
    (
        "N=C(N)NCCC[C@H](N)C(=O)O",
        "(2S)-2-amino-5-(diaminomethylideneamino)pentanoic acid",
    ),
    (
        "N=C(N)NCCC[C@@H](N)C(=O)O",
        "(2R)-2-amino-5-(diaminomethylideneamino)pentanoic acid",
    ),
    (
        "N[C@@H](Cc1cnc[nH]1)C(=O)O",
        "(2S)-2-amino-3-(1H-imidazol-5-yl)propanoic acid",
    ),
    (
        "N[C@H](Cc1cnc[nH]1)C(=O)O",
        "(2R)-2-amino-3-(1H-imidazol-5-yl)propanoic acid",
    ),
    ("NC(Cc1cnc[nH]1)C(=O)O", "histidine"),
    ("N[C@@H](CC(=O)O)C(=O)O", "(2S)-2-aminobutanedioic acid"),
    ("N[C@H](CC(=O)O)C(=O)O", "(2R)-2-aminobutanedioic acid"),
    ("N[C@@H](CCC(=O)O)C(=O)O", "(2S)-2-aminopentanedioic acid"),
    ("N[C@H](CCC(=O)O)C(=O)O", "(2R)-2-aminopentanedioic acid"),
    ("O=C(O)C(=O)O", "oxalic acid"),
    ("O=C(O)CC(=O)O", "malonic acid"),
    ("O=C(O)CCCCC(=O)O", "adipic acid"),
    ("O=C(O)/C=C\\C(=O)O", "maleic acid"),
    ("O=C(O)/C=C/C(=O)O", "(E)-but-2-enedioic acid"),
    ("O=C(O)/C=C/c1ccccc1", "(E)-3-phenylprop-2-enoic acid"),
    ("O=C(O)/C=C\\c1ccccc1", "(Z)-3-phenylprop-2-enoic acid"),
    ("O=C(O)c1ccccc1C(=O)O", "phthalic acid"),
    ("O=C(O)c1cccc(C(=O)O)c1", "benzene-1,3-dicarboxylic acid"),
    ("O=C(O)c1ccc(C(=O)O)cc1", "terephthalic acid"),
    (
        "O=C(O)c1cccc(C(=O)O)c1C(=O)O",
        "benzene-1,2,3-tricarboxylic acid",
    ),
    (
        "O=C(O)c1ccc(C(=O)O)c(C(=O)O)c1",
        "benzene-1,2,4-tricarboxylic acid",
    ),
    (
        "O=C(O)c1cc(C(=O)O)cc(C(=O)O)c1",
        "benzene-1,3,5-tricarboxylic acid",
    ),
    (
        "O=C(O)c1ccc(C(=O)O)c(C(=O)O)c1C(=O)O",
        "benzene-1,2,3,4-tetracarboxylic acid",
    ),
    (
        "O=C(O)c1cc(C(=O)O)c(C(=O)O)c(C(=O)O)c1",
        "benzene-1,2,3,5-tetracarboxylic acid",
    ),
    (
        "O=C(O)c1cc(C(=O)O)c(C(=O)O)cc1C(=O)O",
        "benzene-1,2,4,5-tetracarboxylic acid",
    ),
    (
        "O=C(O)c1cc(C(=O)O)c(C(=O)O)c(C(=O)O)c1C(=O)O",
        "benzene-1,2,3,4,5-pentacarboxylic acid",
    ),
    (
        "O=C(O)c1c(C(=O)O)c(C(=O)O)c(C(=O)O)c(C(=O)O)c1C(=O)O",
        "mellitic acid",
    ),
    ("C[C@@H](O)C(=O)O", "(2R)-2-hydroxypropanoic acid"),
    ("C[C@H](O)C(=O)O", "(2S)-2-hydroxypropanoic acid"),
    ("CC(O)C(=O)O", "2-hydroxypropanoic acid"),
    ("O=C(O)C[C@H](O)C(=O)O", "(2S)-2-hydroxybutanedioic acid"),
    ("O=C(O)C[C@@H](O)C(=O)O", "(2R)-2-hydroxybutanedioic acid"),
    ("O=C(O)CC(O)C(=O)O", "2-hydroxybutanedioic acid"),
    (
        "O=C(O)[C@@H](O)[C@H](O)C(=O)O",
        "(2S,3S)-2,3-dihydroxybutanedioic acid",
    ),
    (
        "O=C(O)[C@H](O)[C@@H](O)C(=O)O",
        "(2R,3R)-2,3-dihydroxybutanedioic acid",
    ),
    (
        "O=C(O)[C@@H](O)[C@@H](O)C(=O)O",
        "(2R,3S)-2,3-dihydroxybutanedioic acid",
    ),
    ("O=C(O)C(O)C(O)C(=O)O", "2,3-dihydroxybutanedioic acid"),
    ("O=C(O)CC(O)(CC(=O)O)C(=O)O", "citric acid"),
    ("Nc1ncnc2[nH]cnc12", "7H-purin-6-amine"),
    ("Nc1nc2[nH]cnc2c(=O)[nH]1", "2-amino-3,7-dihydropurin-6-one"),
    ("Nc1ccnc(=O)[nH]1", "cytosine"),
    ("O=c1[nH]cnc2[nH]cnc12", "3,7-dihydropurin-6-one"),
    (
        "O=c1[nH]c(=O)c2[nH]cnc2[nH]1",
        "3,7-dihydropurine-2,6-dione",
    ),
    ("c1ncc2[nH]cnc2n1", "7H-purine"),
    ("O=C([O-])O", "bicarbonate"),
    ("O=C([O-])[O-]", "carbonate"),
    ("O=S(=O)(O)O", "sulfuric acid"),
    ("O=S(O)O", "sulfurous acid"),
    ("O=[N+]([O-])O", "nitric acid"),
    ("O=NO", "nitrous acid"),
    ("Cl", "hydrochloric acid"),
    ("OB(O)O", "boric acid"),
    ("O=C(O)O", "carbonic acid"),
    ("O=[N+]([O-])[O-]", "nitrate"),
    ("O=S(=O)([O-])[O-]", "sulfate"),
    ("NO", "hydroxylamine"),
    ("[NH4+]", "ammonium"),
    ("[OH-]", "hydroxide"),
    ("[F-]", "fluoride"),
    ("[Cl-]", "chloride"),
    ("[Br-]", "bromide"),
    ("[I-]", "iodide"),
    ("[Na+]", "sodium"),
    ("[K+]", "potassium"),
    ("[Li+]", "lithium"),
    ("[Ca+2]", "calcium"),
    ("[Mg+2]", "magnesium"),
    ("[Zn+2]", "zinc"),
    ("[Fe+2]", "iron(2+)"),
    ("[Fe+3]", "iron(3+)"),
    ("[Cu+]", "copper(1+)"),
    ("[Cu+2]", "copper(2+)"),
    ("[Al+3]", "aluminium"),
    ("P", "phosphane"),
    ("PP", "diphosphane"),
    ("O=P(O)(O)O", "phosphoric acid"),
    ("OP(O)O", "phosphorous acid"),
    ("O=[PH](O)O", "hypophosphorous acid"),
    ("B", "borane"),
    ("BB", "diborane"),
    ("[SiH4]", "silane"),
    ("[SiH3][SiH3]", "disilane"),
    ("O=[Se](O)O", "selenious acid"),
    ("O=[Se](=O)(O)O", "selenic acid"),
    ("O=P(O)(O)OP(=O)(O)O", "pyrophosphoric acid"),
    ("Cl[Si](Cl)(Cl)Cl", "tetrachlorosilane"),
    ("Cl[SiH](Cl)Cl", "trichlorosilane"),
    ("Cl[SiH2]Cl", "dichlorosilane"),
    ("[SiH3]Cl", "chlorosilane"),
    ("F[SiH2]F", "difluorosilane"),
    ("ClP(Cl)Cl", "phosphorus trichloride"),
    ("FP(F)F", "phosphorus trifluoride"),
    ("BrP(Br)Br", "phosphorus tribromide"),
    ("IP(I)I", "phosphorus triiodide"),
    ("O=P(Cl)(Cl)Cl", "phosphoryl trichloride"),
    ("O=P(F)(F)F", "phosphoryl trifluoride"),
    ("S=P(Cl)(Cl)Cl", "phosphorothioyl trichloride"),
    ("O=S(Cl)Cl", "thionyl chloride"),
    ("O=S(F)F", "thionyl fluoride"),
    ("O=S(=O)(Cl)Cl", "sulfuryl chloride"),
    ("O=S(=O)(F)F", "sulfuryl fluoride"),
    ("NP(N)(N)=O", "phosphoric triamide"),
    ("NP(N)N", "phosphorous triamide"),
    ("NC(=S)S", "carbamodithioic acid"),
    ("OC(=S)S", "carbonodithioic O-acid"),
    ("O=C=O", "carbon dioxide"),
    ("[C-]#[O+]", "carbon monoxide"),
    ("S=C=S", "carbon disulfide"),
    ("O=C=S", "carbonyl sulfide"),
    ("ClC(Cl)(Cl)Cl", "carbon tetrachloride"),
    ("N", "ammonia"),
    ("N#N", "dinitrogen"),
    ("O=O", "dioxygen"),
    ("ClCl", "dichlorine"),
    ("BrBr", "dibromine"),
    ("II", "diiodine"),
    ("FF", "difluorine"),
    ("OO", "hydrogen peroxide"),
    ("[H][H]", "dihydrogen"),
    ("S", "hydrogen sulfide"),
    ("O", "water"),
    ("C1CCC2CCCCC2C1", "decahydronaphthalene"),
    ("C1CCC2CCCCC2CC1", "decahydronaphthalene"),
    ("[AsH3]", "arsane"),
    ("[SbH3]", "stibane"),
    ("[BiH3]", "bismuthane"),
    ("[GeH4]", "germane"),
    ("[SnH4]", "stannane"),
    ("[PbH4]", "plumbane"),
    ("N=C=N", "methanediimine"),
    ("NNC(N)=O", "semicarbazide"),
    ("NNC(N)=S", "thiosemicarbazide"),
    ("N#CN", "cyanamide"),
    ("C=O", "formaldehyde"),
    ("CC=O", "acetaldehyde"),
    ("Cc1ccccc1", "toluene"),
    ("CC(=O)OC(C)=O", "acetic anhydride"),
    ("O=C(c1ccccc1)c1ccccc1", "diphenylmethanone"),
    ("COC(=O)c1ccccc1O", "methyl salicylate"),
    ("CC#N", "acetonitrile"),
    ("O=C1NC(=O)c2ccccc21", "isoindole-1,3(2H)-dione"),
    ("C=Cc1ccccc1", "styrene"),
    ("O=C(O)CO", "glycolic acid"),
    ("CC(=O)C(=O)O", "pyruvic acid"),
    ("CC(=O)CCC(=O)O", "levulinic acid"),
    ("CC(=O)CC(=O)O", "acetoacetic acid"),
    ("O=C(O)CCl", "chloroacetic acid"),
    ("O=C(O)CBr", "bromoacetic acid"),
    ("O=C(O)CF", "fluoroacetic acid"),
    ("O=C(O)CI", "iodoacetic acid"),
    ("O=C(O)C(Cl)(Cl)Cl", "trichloroacetic acid"),
    ("O=C(O)C(Cl)Cl", "dichloroacetic acid"),
    ("O=C(O)C(F)(F)F", "trifluoroacetic acid"),
    ("O=C(O)C(F)F", "difluoroacetic acid"),
    ("O=C(O)Cc1ccccc1", "phenylacetic acid"),
    ("O=C(O)c1ccccc1O", "salicylic acid"),
    ("S=C(S)S", "trithiocarbonic acid"),
    ("COC(=O)CN", "methyl glycinate"),
    ("CCOC(=O)CN", "ethyl glycinate"),
    ("COC(=O)C(C)N", "methyl alaninate"),
    ("CCOC(=O)C(C)N", "ethyl alaninate"),
    ("COC(=O)[C@@H](C)N", "methyl L-alaninate"),
    ("CCOC(=O)[C@@H](C)N", "ethyl L-alaninate"),
    ("COC(=O)[C@H](C)N", "methyl D-alaninate"),
    ("CCOC(=O)[C@H](C)N", "ethyl D-alaninate"),
];
